
spring:
  application:
    name: api-gateway
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
server:
  port: 8082
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
  #排除某些路由
  ignored-patterns:
    - /product/product/listForOrder
    - /myProduct/product/listForOrder
#简洁写法
#zuul:
#  routes:
#    product: /myProduct/**
management:
  endpoints:
    web:
      exposure:
        include: "*"