
spring:
  application:
    name: order
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: admin
    url: jdbc:mysql://127.0.0.1/springcloud_sell?characterEncoding=utf-8&useSSL=false
  jpa:
      show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  cloud:
    stream:
      bindings:
        input:
          destination: myMessage
          group: order
        output:
          destination: myMessage
          group: order
  redis:
    host: localhost
    port: 6379
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: web # 设置使用http的方式传输数据
  sleuth:
    sampler:
      probability: 1 # 设置抽样采集为100%，默认为0.1，即10%
#  cloud:
#    config:
#      discovery:
#        enabled: true
#        service-id: CONFIG
#      profile: dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
env:
  dev
#使用配置项配置熔断超时时间
hystrix:
  command:
    defalut:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
    getProductInfoList:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
#与feign结合使用熔断功能
feign:
  hystrix:
    enabled: true
logging:
  level:
    org.springframework.cloud.openfeign: debug